/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 naruto_sage_mode.glb --transform --simplify 
Files: naruto_sage_mode.glb [11.79MB] > naruto_sage_mode-transformed.glb [835.55KB] (93%)
Author: ℕ𝕒𝕥𝕤𝕦 𝕕𝕣𝕒𝕘𝕟𝕖𝕖𝕝 (https://sketchfab.com/Naruto4788555964)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/naruto-sage-mode-8861959f2dc14b20afb6ae164ba1b516
Title: Naruto Sage Mode
*/

import * as THREE from 'three';
import React, {useRef} from 'react'
import {MeshReflectorMaterial, Sparkles, useGLTF} from '@react-three/drei'
// import {Glass} from "@/components/canvas/materials/glass";

export function NarutoModel(props) {
  const {nodes, materials} = useGLTF('/models/naruto_sage_mode-transformed.glb');
  // materials['Scene_-_Root'];

  console.log('___', materials['Scene_-_Root'])

  // materials['Scene_-_Root'].receiveShadow = true;
  // materials['Scene_-_Root'].color = new THREE.Color(0x000000);

  materials['Scene_-_Root'].roughness = .87;
  materials['Scene_-_Root'].metalness = 0;
  materials['Scene_-_Root'].emissive = new THREE.Color(0x000000);
  materials['Scene_-_Root'].color = new THREE.Color(0x000000)


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]}>
        {/*<Glass color={'#000'} />*/}
        {/*<MeshReflectorMaterial*/}
        {/*  blur={[300, 50]}*/}
        {/*  resolution={1024}*/}
        {/*  mixBlur={1}*/}
        {/*  mixStrength={100}*/}
        {/*  roughness={1}*/}
        {/*  depthScale={1.2}*/}
        {/*  minDepthThreshold={0.4}*/}
        {/*  maxDepthThreshold={1.4}*/}
        {/*  color="#202020"*/}
        {/*  metalness={0.8}*/}
        {/*/>*/}

      </mesh>
    </group>
  )
}

useGLTF.preload('/models/naruto_sage_mode-transformed.glb')
