/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ice_block.glb -T -S 
Files: ice_block.glb [2.01MB] > ice_block-transformed.glb [335.1KB] (83%)
Author: bilgehan.korkmaz (https://sketchfab.com/bilgehan.korkmaz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ice-block-66efdeab7d214907b32bbcb47d9b55ad
Title: Ice Block
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function IceBlockModel(props) {
  const { nodes, materials } = useGLTF('/models/ice_block-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} />
    </group>
  )
}

useGLTF.preload('/models/ice_block-transformed.glb')
